### ISSUE TITLE
CSP inline-script error

### ISSUE THREAD

**Issue by rlivsey** [binhums/ember-cli-bugsnag#21]
Chrome gives the following CSP error when using the addon:

```
[Report Only] Refused to execute inline script because it violates the following 
Content Security Policy directive: "script-src ... ". Either the 'unsafe-inline' keyword, 
a hash ('sha256-Li1kX2hSsXxBIvK1YWeekOV49Asr5QAOvrIrILWqql0='), or a 
nonce ('nonce-...') is required to enable inline execution.
```

It would be reasonably straightforward to generate a hash of the contents and inject that into the CSP rules in development, but I'm not sure how this would work in production. Obviously the addon doesn't integrate with the web-server in any way so there'd be no way of injecting this.

Adding a nonce to the config and using that in the script tag would also work, we'd just need to use the same nonce in the web-server config for it to work on live.

Another approach would be to not inject the script tag into the HTML at build time at all and instead dynamically inject the script at run-time using something like [ember-inject-script](https://github.com/minutebase/ember-inject-script).

**Comment by jamesarosen** [comment]
The inline script tag includes
```js
Bugsnag.releaseStage = "production";
Bugsnag.notifyReleaseStages = ["production"];
```
Could we move that to an initializer? Or is that too late? What would happen if a bug occurred before the initializer ran?

Perhaps the right answer is to ask the Bugsnag folks to have the library support those options as `data-` attributes on the Bugsnag `<script>` tag like `data-appversion` and `data-apikey`.

**Comment by thegranddesign** [comment]
@twokul what's the plan here?  I'd like to get this error out of my console.

**Comment by binhums** [comment]
@jamesarosen, @thegranddesign I've put together my throughts here in #45. Let me know what you think.
