### ISSUE TITLE
Latest version not on npm

### ISSUE THREAD

**Issue by patrickberkeley** [binhums/ember-cli-bugsnag#46]
The latest version published to npm is `0.1.5`.

**Comment by binhums** [comment]
@patrickberkeley thanks for raising, should be up now:

https://www.npmjs.com/package/ember-cli-bugsnag

Let me know if you run into anything using this.

**Comment by binhums** [comment]
Also if you're interested in test driving some of the code in https://github.com/binhums/ember-cli-bugsnag/pull/45 I'd be interested to see how you get on with it.

**Comment by patrickberkeley** [comment]
Thank you!
