### ISSUE TITLE
User id is always IP address

### ISSUE THREAD

**Issue by timiyay** [binhums/ember-cli-bugsnag#48]
I'm assuming this is an upstream issue, and I've reported it as https://github.com/bugsnag/bugsnag-js/issues/171.

Nonetheless, I wanted to note it here.

I'm hitting an annoyance, when adding user metadata to my exception - my user ID is being ignored, and the default IP address is always being used instead.

**Comment by timiyay** [comment]
I haven't figured this out yet, but I'm feeling comfortable the issue isn't `ember-cli-bugsnag`, and probably not anything on the client side.

**Comment by binhums** [comment]
Hi @timiyay I'm assuming that #49 is the issue here?

**Comment by timiyay** [comment]
@binhums no they're unrelated.

I'll need to reopen this issue, based on Bugsnag's feedback here: https://github.com/bugsnag/bugsnag-js/issues/171#issuecomment-238175756

It has now morphed into a feature request. I need a way to set the top-level `user` object in a bugsnag request. Embedding `user` inside `metadata` isn't supposed to work, apparently.

**Comment by timiyay** [comment]
PR here: https://github.com/binhums/ember-cli-bugsnag/pull/50

**Comment by binhums** [comment]
Fixed in #71. Thanks for your work towards this @timiyay, sorry it took so long to resolve.

**Comment by binhums** [comment]
Released in [v1.2.0](https://github.com/binhums/ember-cli-bugsnag/releases/tag/v1.2.0).
