### ISSUE TITLE
Can't return promise from getMetaData

### ISSUE THREAD

**Issue by timiyay** [binhums/ember-cli-bugsnag#49]
In our Ember app, we have a `currentUser` computed property on our session service, which returns a promise.

I'm hoping to use this `currentUser()` method to populate the Bugsnag `user` metadata via this promise-based method. However, returning a promise from `utils/bugsnag.js getMetadata()` is not currently possible.

Do you forsee this being possible? Or will I have to develop a local workaround?

**Comment by binhums** [comment]
Hi @timiyay. You're welcome to look into a local workaround for now certainly or even write a PR.

My question is how do we handle the case when the promise won't return. E.g. if there's some kind of fatal issue with Ember and we can't access the service then bug will be reported. Is there a way you can think of building in a fallback?

**Comment by binhums** [comment]
In the light of work on #50 would it make sense to update that user metadata when your computed property changes?

**Comment by timiyay** [comment]
@binhums yes I'll try and alternative approach. I took a quick look at adding promise support, but could only think of an ugly-ish solution involving `if (typeof metadata.then === 'function') {}`.

Will see how I go, and close this if I can deal with the promise elsewhere.

**Comment by binhums** [comment]
Thanks, excited to see what you turn up. Let me know if you need any assistance. I'm usually on emberjs community slack.

**Comment by timiyay** [comment]
I was able to do this by making more-considered use of my existing promises in CPs in my `session` service.

**Comment by binhums** [comment]
Great :+1:
