### ISSUE TITLE
1.0.0+ always thinks I am in production

### ISSUE THREAD

**Issue by robclancy** [binhums/ember-cli-bugsnag#54]
`1.0.0+` always thinks I am in production so is always logging when in development. I made sure it was properly in development still checking right before an error occurred.

I went through code and couldn't find out why, mine and yours. But it works fine on `0.2.0` so just sticking with that as I haven't got time to find the actual issue or diff what changed between versions.

**Comment by binhums** [comment]
OK, makes sense. Could you add your bugsnag config from `environment.js` or the environment variables you use? Don't forget to hide your API key if posting publicly.

**Comment by robclancy** [comment]
It's just
```
bugsnag: {
      apiKey: 'xxxx',
      notifyReleaseStages: ['production'],
    },
```

The environment sent to bugsnag is production though so it thinks it is production, I checked in the request sent as well and it sends `releaseStage` as `production` in it.

**Comment by binhums** [comment]
Got it, thanks for reporting. I'll have a little dig around.

**Comment by binhums** [comment]
Thanks for your patience, should be good with [v1.0.2](https://github.com/binhums/ember-cli-bugsnag/releases/tag/v1.0.2)
