### ISSUE TITLE
Get bugsnag-js from npm instead of Bower

### ISSUE THREAD

**Issue by josemarluedke** [binhums/ember-cli-bugsnag#58]
Since emberjs/ember.js#13022 has been merged, it would be very nice to get rid of the bower dependency and start using the npm version of the bugsnag. 

https://github.com/bugsnag/bugsnag-js
https://www.npmjs.com/package/bugsnag-js

**Comment by binhums** [comment]
Again, yes! Let's do it. What do I need to know to get us there?
