### ISSUE TITLE
Fastboot support

### ISSUE THREAD

**Issue by josemarluedke** [binhums/ember-cli-bugsnag#59]
Any plans on getting fastboot support out of the box for this addon?

The ideal would be that this addon uses the node version of bugsnag when running in fastboot, and then when running in the browser it uses the JS version. 

First step, at least, is to get this to not include the browser version of JS in fastboot land.

**Comment by binhums** [comment]
I absolutely intend to get this on fastboot. I don't know anything about it and I'm on holiday so we will be a few weeks before this lands. That said I'd love to pair with you, and any advice you have is appreciated.

Ben
