### ISSUE TITLE
How to require bugsnag

### ISSUE THREAD

**Issue by anthonycollini** [binhums/ember-cli-bugsnag#64]
I need to require Bugsnag in a before hook to the ember build. 

I have no problem requiring it when I install it using npm: `npm install bugsnag --save-dev`

However, I think since it's an ember-cli add-on, I'm having issues.

Docs say to `require('bugsnag')`, but it doesn't seem available at this stage.

Do you have any thoughts on how I can require it in a file outside the app directory in the tasks directory, and before ember gets built ?

**Comment by binhums** [comment]
Using `npm install bugsnag --save-dev` seems appropriate if you need bugsnag outside of Ember.

Were you running into trouble with this method?

**Comment by binhums** [comment]
Can you provide any more specifics about what you're hoping to achieve? It's always good to understand use cases / motivation for me.

**Comment by anthonycollini** [comment]
I need to customize .scss files depending on the server I deploy to, so I need access to Bugsnag outside of the ember context as the javascript file that gets run in a before_hook (that changes the scss files) needs to report to bugsnag if there's an error in this customization file. I installed it through npm and was able to require it into the file. Will there be any issues with installing it using npm as well as using the ember addon?

**Comment by binhums** [comment]
Seems like a fine approach, did you have any troubles with it?

The only thing to look out for is making sure that the versions of bugsnag match.
