### ISSUE TITLE
Library URL config option

### ISSUE THREAD

**Issue by jeffjewiss** [binhums/ember-cli-bugsnag#66]
Thanks for putting this add-on together, it was really easy to setup.

I was wondering if the `config.bugsnag.libraryUrl` property is still relevant. From what I can tell the add-on was updated to pull the Bugsnag library from Bower and then, more recently, to use inline node assets to use the node module.

Thanks!

**Comment by binhums** [comment]
Hi @jeffjewiss glad it works well for you. It could probably do with some maintenance work though :)

My gut feeling is that libraryUrl got dropped but we forgot to drop it from the README. Is this something that you need?

**Comment by jeffjewiss** [comment]
No worries, let me know if I could help in some way. Cheers.

**Comment by binhums** [comment]
Thanks @jeffjewiss
